apiVersion: v1
kind: Service
metadata:
  name: lib-manager-react-ts
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: lib-manager-react-ts
  type: ClusterIP
