name: Build and test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'Makefile'
      - deploy/**

jobs:
  build:
    strategy:
      matrix:
        node-version: [ '23.8.0' ]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Download dependencies
        run: npm install
      - name: Build the code
        run: npm run build
      - name: Run tests
        run: npm run test:run
      - name: Add broker CA
        env:
          CA_SECRET: ${{ secrets.PACT_BROKER_CA }}
        shell: bash
        run: |
          printf '%s' "${CA_SECRET}" > pact-broker-ca.pem
        # Using Docker Run inside of Gitea Actions - https://gitea.com/gitea/act_runner/issues/189
        # https://hub.docker.com/r/pactfoundation/pact-cli
      - name: Publish Pact files
        uses: addnab/docker-run-action@v3
        with:
          image: pactfoundation/pact-cli:latest
          options: >
            --volumes-from=${{ env.JOB_CONTAINER_NAME }} 
            -e PACT_DO_NOT_TRACK=true 
            -e SSL_CERT_FILE=pact-broker-ca.pem
          docker_network: gitea
          run: |
            cd ${{ gitea.workspace }}
            pact publish pacts \
            --broker-base-url ${{ vars.PACT_BROKER_BASE_URL }} \
            --auto-detect-version-properties \
            --consumer-app-version ${{ env.GITHUB_SHA }} \
            --branch ${{ env.GITHUB_HEAD_REF }}
