apiVersion: apps/v1
kind: Deployment
metadata:
  name: lib-manager-react-ts
spec:
  template:
    spec:
      containers:
        - name: lib-manager-react-ts
          resources:
            requests:
              cpu: '0.1'
              memory: '64Mi'
            limits:
              cpu: '0.2'
              memory: '128Mi'
